- wp-content/themes/humanity-theme/includes/blocks/header/class-header-block-renderer.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/9
1. Add a header block to a page
2. Populate with content
3. In the Header title, partially highlight the title (2 words for example)
4. Set them to bold, save and view the front end
5. All spaces should remain as originally set in the editor
Example: 
http://bigbite.im/i/tmV644
http://bigbite.im/i/VqLi9z
> Bold Text on Header Spacing

- wp-content/themes/humanity-theme/includes/mlp/language-selector.php
Ref https://github.com/amnestywebsite/amnesty-wp-theme/issues/2833
When multiple sites exist with the same ISO 639
2-letter code, because we index the site list
by that code, only the last one to be set will
appear in said list.
This change instead indexes numerically, to
resolve collision issues such as this.
Test in conjunction with https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/8
1. Add a site that uses the same 2 letter language code as an existing site
2. Connect it to the other sites using MultilingualPress
3. Visit a homepage
4. The language selector should show the new site, as well as the existing sites
5. Connect an existing post to a duplicate post on the new site using MultilingualPress
6. Visit the post
7. The language selector should …
> Fix site language collisions

- private/src/styles/blocks/core-blocks/_latest-posts.scss
- private/src/styles/pages/article/_sidebar.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/33
Ensures all blocks used within the sidebar have equal widths and fill the available space
1. Create a sidebar
2. Insert a number of blocks
3. Add sidebar to a post and view front end
4. Check all blocks fill the available sidebar space and are equal in width
Example: http://bigbite.im/v/dHhs4K
> Sidebar Block Widths

- .travis.yml
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2851
> Add 2 new deployment targets (STG + PRD)

- private/src/styles/app.scss
- private/src/styles/blocks/list-block/_editor.scss
- private/src/styles/blocks/list-block/_main.scss
- private/src/styles/blocks/list-block/_shared.scss
- private/src/styles/gutenberg.scss
- wp-content/themes/humanity-theme/functions.php
- wp-content/themes/humanity-theme/includes/helpers/list-alignment.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/10
1. Add a list block to a post
2. Select the list block and view the toolbar
3. There should now be an option for alignment
4. Switch between the alignments, ensuring the list block changes appropriately 
5. Save and check the same on the front end
Example: http://bigbite.im/v/2XDND4
> Add Alignment Styles To The List Block

- wp-content/themes/humanity-theme/includes/blocks/raw-code/register.php
- wp-content/themes/humanity-theme/includes/blocks/register.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/147
1. Edit a post
2. Check the Raw Code block appears in the block editor
3. Check the block works as expected
Example: 
http://bigbite.im/i/OWGdSl
http://bigbite.im/i/UyoPTL
> Register Raw Code block in PHP

- private/src/scripts/editor/blocks/stat-counter/deprecated.jsx
- private/src/scripts/editor/blocks/stat-counter/index.jsx
- private/src/styles/blocks/stat-counter/_main.scss
- wp-content/themes/humanity-theme/includes/blocks/background-media/render.php
- wp-content/themes/humanity-theme/includes/blocks/blockquote/render.php
- wp-content/themes/humanity-theme/includes/blocks/custom-card/render.php
- wp-content/themes/humanity-theme/includes/blocks/header/class-header-block-renderer.php
- wp-content/themes/humanity-theme/includes/blocks/image/render.php
- wp-content/themes/humanity-theme/includes/blocks/post-list/views/grid-item-meta.php
- wp-content/themes/humanity-theme/includes/blocks/post-list/views/grid-item-title.php
- wp-content/themes/humanity-theme/includes/blocks/post-list/views/grid-item.php
- wp-content/themes/humanity-theme/includes/blocks/post-list/views/list-item-meta.php
- wp-content/themes/humanity-theme/includes/blocks/post-list/views/list-item-title.php
- wp-content/themes/humanity-theme/includes/blocks/regions/render.php
- wp-content/themes/humanity-theme/includes/blocks/register.php
- wp-content/themes/humanity-theme/includes/blocks/section/class-section-block-renderer.php
- wp-content/themes/humanity-theme/includes/blocks/stat-counter/register.php
- wp-content/themes/humanity-theme/includes/blocks/stat-counter/render.php
- wp-content/themes/humanity-theme/includes/helpers/array-manipulation.php
- wp-content/themes/humanity-theme/includes/helpers/class-classnames.php
- wp-content/themes/humanity-theme/includes/helpers/variable-types.php
- wp-content/themes/humanity-theme/includes/mlp/helpers.php
- wp-content/themes/humanity-theme/partials/archive/filters-active.php
- wp-content/themes/humanity-theme/partials/petitions/item.php
Ref: [#145](https://github.com/amnestywebsite/humanity-theme/issues/145)
Registers the counter block in PHP to add FSE support, also changes the render to PHP
1.  Edit a post
2. Check if counter block appears in the block inserter
3. Add the block and content
4. Save and view the front end
5. Check block functions as expected
Example: http://bigbite.im/i/kn8U03
> Register and render the counter block in PHP

- private/src/scripts/editor/blocks/countdown-timer/deprecated.jsx
- private/src/scripts/editor/blocks/countdown-timer/index.jsx
- private/src/styles/blocks/countdown-timer/_editor.scss
- private/src/styles/blocks/countdown-timer/_main.scss
- wp-content/themes/humanity-theme/includes/blocks/background-media/render.php
- wp-content/themes/humanity-theme/includes/blocks/blockquote/render.php
- wp-content/themes/humanity-theme/includes/blocks/countdown-timer/register.php
- wp-content/themes/humanity-theme/includes/blocks/countdown-timer/render.php
- wp-content/themes/humanity-theme/includes/blocks/custom-card/render.php
- wp-content/themes/humanity-theme/includes/blocks/header/class-header-block-renderer.php
- wp-content/themes/humanity-theme/includes/blocks/image/render.php
- wp-content/themes/humanity-theme/includes/blocks/post-list/views/grid-item-meta.php
- wp-content/themes/humanity-theme/includes/blocks/post-list/views/grid-item-title.php
- wp-content/themes/humanity-theme/includes/blocks/post-list/views/grid-item.php
- wp-content/themes/humanity-theme/includes/blocks/post-list/views/list-item-meta.php
- wp-content/themes/humanity-theme/includes/blocks/post-list/views/list-item-title.php
- wp-content/themes/humanity-theme/includes/blocks/regions/render.php
- wp-content/themes/humanity-theme/includes/blocks/register.php
- wp-content/themes/humanity-theme/includes/blocks/section/class-section-block-renderer.php
- wp-content/themes/humanity-theme/includes/helpers/array-manipulation.php
- wp-content/themes/humanity-theme/includes/helpers/class-classnames.php
- wp-content/themes/humanity-theme/includes/helpers/variable-types.php
- wp-content/themes/humanity-theme/includes/mlp/helpers.php
- wp-content/themes/humanity-theme/partials/archive/filters-active.php
- wp-content/themes/humanity-theme/partials/petitions/item.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/148
Reworks the countdown timer to be rendered in PHP to bring in line with FSE
1. Edit a post
2. Countdown timer should be show in the block inserter
3. Add the block, populate and save
4. View the front end and make sure the block displays as expected
Example: http://bigbite.im/i/5f672I
> Renders the countdown block in php for FSE

- private/src/scripts/editor/blocks/call-to-action/deprecated.jsx
- private/src/scripts/editor/blocks/call-to-action/index.jsx
- private/src/styles/blocks/call-to-action/_base.scss
- private/src/styles/blocks/call-to-action/_editor.scss
- wp-content/themes/humanity-theme/includes/blocks/background-media/render.php
- wp-content/themes/humanity-theme/includes/blocks/blockquote/render.php
- wp-content/themes/humanity-theme/includes/blocks/call-to-action/register.php
- wp-content/themes/humanity-theme/includes/blocks/call-to-action/render.php
- wp-content/themes/humanity-theme/includes/blocks/custom-card/render.php
- wp-content/themes/humanity-theme/includes/blocks/header/class-header-block-renderer.php
- wp-content/themes/humanity-theme/includes/blocks/image/render.php
- wp-content/themes/humanity-theme/includes/blocks/post-list/views/grid-item-meta.php
- wp-content/themes/humanity-theme/includes/blocks/post-list/views/grid-item-title.php
- wp-content/themes/humanity-theme/includes/blocks/post-list/views/grid-item.php
- wp-content/themes/humanity-theme/includes/blocks/post-list/views/list-item-meta.php
- wp-content/themes/humanity-theme/includes/blocks/post-list/views/list-item-title.php
- wp-content/themes/humanity-theme/includes/blocks/regions/render.php
- wp-content/themes/humanity-theme/includes/blocks/register.php
- wp-content/themes/humanity-theme/includes/blocks/section/class-section-block-renderer.php
- wp-content/themes/humanity-theme/includes/helpers/array-manipulation.php
- wp-content/themes/humanity-theme/includes/helpers/class-classnames.php
- wp-content/themes/humanity-theme/includes/helpers/variable-types.php
- wp-content/themes/humanity-theme/includes/mlp/helpers.php
- wp-content/themes/humanity-theme/partials/archive/filters-active.php
- wp-content/themes/humanity-theme/partials/petitions/item.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/142
1. Edit a post, the Call to Action block should now appear in the block inserter
2. Add a CTA block and populate with content
3. Save and view the front end.
4. CTA should display as expected
Example: http://bigbite.im/i/wR98Yf
> Call to Action FSE Support

- wp-content/themes/humanity-theme/includes/blocks/banner/register.php
- wp-content/themes/humanity-theme/includes/blocks/register.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/141
1. Edit a post
2. Check the Header block appears in the block inserter
3. Check the Banner also appears in the block inserter
4. Add both, and populate with content
5. Save and view the front end, check if they display as expected
For deprecations, add the blocks BEFORE checking out this branch, then switch and check they work and display as expected
> Register the header block in PHP

- private/package.json
- private/src/scripts/editor/blocks/embed-flourish/DisplayComponent.jsx
- private/src/scripts/editor/blocks/iframe-button/DisplayComponent.jsx
- private/src/scripts/editor/blocks/utils.js
- private/src/styles/blocks/iframe-button/_editor.scss
- private/yarn.lock
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2908
1. Edit a post containing an existing Flourish embed
2. The block should load without error
3. Create a new Flourish embed
4. You should be able to add the code without issue
5. The block should not error
6. Add an Iframe Button block
7. You should be able to type in a URL without issue (note that a trailing slash will be automatically added if you are manually typing)
8. Add an Iframe block
9. You should be able to type in a URL without issue (note that a trailing slash will be automatically added if you are manually typing)
> Fix Flourish Embeds

- wp-content/themes/humanity-theme/includes/block-patterns/pattern-category.php
- wp-content/themes/humanity-theme/patterns/evergreen-text-highlight.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/186
Adds evergreen text highlight block pattern
Steps to test:
1. Edit a post
2. Open the block inserter and check the new pattern appears under the patterns tab
3. Insert the pattern and check it matches the example in the ticket
Example: http://bigbite.im/i/GzMX44
> Adds evergreen text highlight block pattern

- wp-content/themes/humanity-theme/includes/taxonomies/class-taxonomy-topics.php
1. before checking out branch
2. visit `[local.domain]//404`
3. see a fatal error
4. check out branch
5. reload page
6. see the 404 page
> Ensure path is always set in redirect regex match

- wp-content/themes/humanity-theme/patterns/web-report.php
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2932
1. Edit a post
2. Open the block inserter, and navigate to patterns
3. Check the web report pattern is present and matches the example given in the ticket
Example: http://bigbite.im/i/kpJDAh
> Creates the web report post pattern

- wp-content/themes/humanity-theme/patterns/press-release-plus-template.php
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2933
Adds press release plus template block pattern
Steps to test:
1. Edit a post
2. Open the block inserter, and navigate to patterns
3. Check the web report pattern is present and matches the example given in the ticket
Example: http://bigbite.im/i/bzKY0H
> Adds press release plus template block pattern

- wp-content/themes/humanity-theme/patterns/issue-post-template.php
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2935
Adds the Issue Post Template Pattern
Steps to test:
1. Edit a post
2. Open the block inserter, and navigate to patterns
3. Check the web report pattern is present and matches the example given in the ticket
Example: http://bigbite.im/i/7F9Bob
> Adds the Issue Post Template Pattern

- wp-content/themes/humanity-theme/includes/block-patterns/pattern-category.php
- wp-content/themes/humanity-theme/patterns/33-33-33-links-with-icons-square.php
- wp-content/themes/humanity-theme/patterns/33-33-33-links-with-icons.php
- wp-content/themes/humanity-theme/patterns/50-50-text-with-image-grey-left.php
- wp-content/themes/humanity-theme/patterns/50-50-text-with-image-grey-right.php
- wp-content/themes/humanity-theme/patterns/50-50-text-with-image-white-left.php
- wp-content/themes/humanity-theme/patterns/50-50-text-with-image-white-right.php
- wp-content/themes/humanity-theme/patterns/50-50-text-with-video-left-grey.php
- wp-content/themes/humanity-theme/patterns/50-50-text-with-video-left.php
- wp-content/themes/humanity-theme/patterns/50-50-text-with-video-right-grey.php
- wp-content/themes/humanity-theme/patterns/50-50-text-with-video-right.php
- wp-content/themes/humanity-theme/patterns/66-33-chapter.php
- wp-content/themes/humanity-theme/patterns/66-33-text-key-facts.php
- wp-content/themes/humanity-theme/patterns/66-33-text-with-image.php
- wp-content/themes/humanity-theme/patterns/66-33-text-with-video.php
- wp-content/themes/humanity-theme/patterns/chunky-heading-with-links.php
- wp-content/themes/humanity-theme/patterns/evergreen-text-highlight.php
- wp-content/themes/humanity-theme/patterns/full-image-with-buttons.php
- wp-content/themes/humanity-theme/patterns/issue-post-template.php
- wp-content/themes/humanity-theme/patterns/links-with-icons-single-square.php
- wp-content/themes/humanity-theme/patterns/links-with-icons-single.php
- wp-content/themes/humanity-theme/patterns/perspective-post-template.php
- wp-content/themes/humanity-theme/patterns/press-release-plus-template.php
- wp-content/themes/humanity-theme/patterns/web-report.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/184
1. visit wp-admin -> appearance -> editor -> patterns
2. you should see a list of categories with patterns within them
> Refine pattern categories

- private/src/scripts/editor/blocks-deprecated/banner/DisplayComponent.jsx
- private/src/scripts/editor/blocks-deprecated/header/DisplayComponent.jsx
- private/src/scripts/editor/blocks/hero/DisplayComponent.jsx
- private/src/scripts/editor/blocks/hero/replaceHeaders.js
- private/src/scripts/editor/components/MediaMetadata.jsx
- wp-content/themes/humanity-theme/functions.php
- wp-content/themes/humanity-theme/includes/blocks/hero/helpers.php
- wp-content/themes/humanity-theme/includes/blocks/hero/render.php
- wp-content/themes/humanity-theme/includes/blocks/register.php
- wp-content/themes/humanity-theme/includes/blocks/render-header-on-single.php
- wp-content/themes/humanity-theme/includes/helpers/blocks.php
- wp-content/themes/humanity-theme/single.php
Ref: N/A
1. create a new **post**
2. add a featured image
3. add a hero block
4. the image metadata should show
5. the image metadata visibility settings should function (and only show once)
6. save the post and view the frontend
7. the featured image should not be visible
8. the hero block should appear where the featured image would be
9. the hero block should not be duplicated in the content of the post
10. in `editor/blocks/hero/replaceHeaders.js`, change the event name on line 77 to something that doesn't exist (to prevent the code from running)
11. rebuild assets
12. create a new **post**
13. add an old header block (via code editor: ``)
14. add an old banner block (via code editor: ``)
15. the header block should still inherit the featured image
16. the image …
> Fix issues with rendering the Hero and its forebears

- wp-content/themes/humanity-theme/patterns/66-33-text-with-video.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/174
Adds heading block to the 66/33 text with video block pattern
1. Edit a post
2. Open the block inserter and click the patterns tab
3. Find and insert the 66/33 text with video pattern
4. The pattern should now include a heading block at the top of the pattern
Example: http://bigbite.im/i/9U73IO
> Pattern - 66 - 33 - Heading Block

- wp-content/themes/humanity-theme/author.php
> Ensure author banner ID is an int in template

- private/src/styles/blocks/core-blocks/_group.scss
Ref: #180 #181 (See comments about text padding)
1.  Edit a post
2. Add a pattern that contains the new LWI group patterns
3. Ensure they have the squared block style
4. Add text and check the padding (Text should not reach either side).
5. Save and check the same on the front end
Example: http://bigbite.im/i/G50wmV
> Square Style Group Padding

- .travis.yml
Should allow PR builds from forks to run
Ref: N/A
> Move secret decryption to deployment steps

- README.md
Just a small fix in the markdown of the README.
> Fix rendering issue in README.md

- wp-content/themes/humanity-theme/includes/taxonomies/class-taxonomy-resource-types.php
Recreated from https://github.com/amnestywebsite/amnesty-wp-theme/pull/2546
> Ensure there's a fallbck path when parsing URL

- private/src/styles/app.scss
- private/src/styles/blocks/core-blocks/_cover.scss
- wp-content/themes/humanity-theme/patterns/background-media-left-grey.php
- wp-content/themes/humanity-theme/patterns/background-media-left-white.php
- wp-content/themes/humanity-theme/patterns/background-media-right-grey.php
- wp-content/themes/humanity-theme/patterns/background-media-right-white.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/290
Creates 4 new block patterns to replace the Background Media block.
1. Edit a post
2. Open the block inserter and navigate to the patterns tab
3. Under "Two Columns" or "1/2 1/2" categories, you should see 4 new patterns for variations of the BM block
4. Insert them all and populate with content
5. They should work and display inline with the original BM block
6. Save and check the front end as well
Example: http://bigbite.im/v/X9iMb7
> Background Media Block Pattern

- private/src/styles/pages/article/_base.scss
- wp-content/themes/humanity-theme/patterns/hero.php
- wp-content/themes/humanity-theme/patterns/page-content.php
- wp-content/themes/humanity-theme/single.php
- wp-content/themes/humanity-theme/templates/page.html
Re https://github.com/amnestywebsite/humanity-theme/pull/371#discussion_r1752051984 and our discussion in Slack, @Gentyspun, something like this would sort out the hero/title output and whatnot. See what you think?
> Fixup template layout and render hero block

- wp-content/themes/humanity-theme/includes/taxonomies/class-taxonomy-locations.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/324
1. disable the theme companion, if applicable
2. edit a location term
3. within a metabox, there should be a featured image field
4. add a featured image
5. re-enable the theme companion, if applicable
6. view the term frontend
7. the featured image should render
8. checkout https://github.com/amnestywebsite/wp-plugin-theme-companion/pull/60
9. edit the location term again
10. the featured image field should not be duplicated
> Add featured image to locations taxonomy

- private/src/styles/blocks/core-blocks/post/_main.scss
- wp-content/themes/humanity-theme/patterns/author-bio.php
- wp-content/themes/humanity-theme/patterns/author-loop.php
- wp-content/themes/humanity-theme/templates/author.html
1. visit the site editor
2. load up the author template
3. blocks should render correctly
4. visit your author archive page
5. the page should render correctly
> FSE author template fixes

- private/src/styles/pages/article/_base.scss
- wp-content/themes/humanity-theme/patterns/petition-content.php
1. visit the site editor
2. edit the petition single template
3. blocks should not throw invalidation errors
> FSE petition single fixes

- private/src/styles/editor.scss
- private/src/styles/pages/_single.scss
- private/src/styles/pages/article/_base.scss
- private/src/styles/pages/article/_editor.scss
- private/src/styles/pages/article/_sidebar.scss
- wp-content/themes/humanity-theme/includes/full-site-editing/blocks/search-header/views/view.php
- wp-content/themes/humanity-theme/patterns/featured-image-hidden.php
- wp-content/themes/humanity-theme/patterns/featured-image.php
- wp-content/themes/humanity-theme/patterns/post-back-link.php
- wp-content/themes/humanity-theme/patterns/post-hero.php
- wp-content/themes/humanity-theme/patterns/post-metadata.php
- wp-content/themes/humanity-theme/patterns/post-published-date.php
- wp-content/themes/humanity-theme/patterns/post-term-list.php
1. visit the site editor
2. edit the single post template
3. blocks should not throw invalidation errors (barring the sidebar, which is addressed in #409)
4. view a single post
5. it should render its data correctly
> FSE single template fixes

- private/src/scripts/editor/fse-blocks/sidebar/DisplayComponent.jsx
- wp-content/themes/humanity-theme/includes/theme-setup/scripts-and-styles.php
1. edit the single post template in the site editor
2. the sidebar should render
> Fixup sidebar errors in site editor

- private/src/scripts/blocks.js
- private/src/scripts/editor/fse-blocks/search-header/DisplayComponent.jsx
- private/src/scripts/editor/fse-blocks/search-header/index.jsx
- wp-content/themes/humanity-theme/patterns/search.php
1. visit the site editor
2. edit the searchpage template
3. it should render correctly
> Fix issues rendering the search page in the site editor

- private/src/scripts/editor/blocks-deprecated/custom-card/DisplayComponent.jsx
- private/src/scripts/editor/blocks/section/DisplayComponent.jsx
- private/src/scripts/editor/blocks/section/deprecated.jsx
- private/src/styles/blocks/custom-card/_editor.scss
- private/src/styles/blocks/custom-card/_main.scss
- private/src/styles/components/form/_input-editor.scss
- wp-content/themes/humanity-theme/theme.json
1. visit get-involved and donate
2. the cards should look reasonable
3. edit these pages
4. the cards should look reasonable here, too
> Implement many layout fixes for the custom card block

- wp-content/themes/humanity-theme/includes/features/search/class-search-page.php
- wp-content/themes/humanity-theme/patterns/search.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/449
1. visit /search/
2. attempt to filter by a taxonomy term
3. the filter should apply correctly
4. filter by some additional stuff - year, month, etc
5. they should work
> Fix search page tax filters

- private/src/scripts/editor/fse-blocks/sidebar/DisplayComponent.jsx
- wp-content/themes/humanity-theme/includes/full-site-editing/blocks/sidebar/render.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/450
1. edit a post
2. in appearance options, maximise the content and disable the sidebar
3. save
4. view the frontend
5. the sidebar area should not be present, and the content area should be the width of the container
> Fix typo in content maximisation conditionals

- wp-content/themes/humanity-theme/patterns/page-content.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/454
1. Before checking out this PR
2. Visit the contact page (or any page without a hero)
3. See that the title is missing
4. Checkout this PR
5. Reload the page
6. See that the title is outputted
> Output the page title if there is no hero

- CHANGELOG.md
- wp-content/themes/humanity-theme/sidebar-report.php
- wp-content/themes/humanity-theme/sidebar.php
- wp-content/themes/humanity-theme/style.css
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2988
1. view a country report (requires theme companion)
2. the sidebar should contain the annual report download block
> Fix sidebars

- wp-content/themes/humanity-theme/patterns/post-content.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/470
1. edit a post
2. add a featured image
3. add a hero with a title
4. save
5. view the frontend
6. both the hero and the post title should output correctly
> Always output the post title on single template

- wp-content/themes/humanity-theme/patterns/custom-card-dark.php
- wp-content/themes/humanity-theme/patterns/custom-card-light.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/287
1. insert one custom card pattern of each style
2. check that the aspect ratio on the image is pre-set to 16:9
> Add aspect ratio to custom card patterns' image

- private/src/scripts/editor/blocks/post-list/components/DisplayAuthor.jsx
- private/src/scripts/editor/blocks/post-list/components/DisplayCategories.jsx
- private/src/scripts/editor/blocks/post-list/components/DisplayCustom.jsx
- private/src/scripts/editor/blocks/post-list/components/DisplayFeed.jsx
- private/src/scripts/editor/blocks/post-list/components/DisplayTaxonomies.jsx
- private/src/scripts/editor/blocks/post-list/components/SelectPreview.jsx
- wp-content/themes/humanity-theme/includes/blocks/petition-list/render.php
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2949
Reworks grids for petition list block to match the post list block. Historically, the post list items would stretch to fill space in the grid if the quantity of items was not divisible by 4 when there are fewer than 8 items; whereas the petition list block would not replicate this, and would always render as a 4 column grid. 
It also cleans up the display components, so that the output is organised more logically.
1. before checking out this PR. create a new post, and add some post list blocks with varying quantities of items. A HTML snippet below has been provided to make this easier.
2. review how the blocks are rendered in both the block editor and on the frontend in varying screen sizes.
3. checkout …
> Adjust grids to correctly calculate layouts

- .travis.yml
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/3005
Removes an old target and adds new STG/PRD targets
**Steps to test:**
Conformance check only
> Update deployment targets

- wp-content/themes/humanity-theme/patterns/search.php
Ref: N/A. Discovered during implementation of https://github.com/amnestywebsite/humanity-theme/issues/481
1. before checking out this PR
2. visit the search page in a non-EN lang (FR/AR/ES)
3. scroll down to the pagination 
4. see that next/previous are in English
5. checkout this PR
6. reload the page
7. next/previous should be translated correctly
> Fix missing localisation in search pattern

- .travis.yml
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/3009
> Add new deployment targets

- wp-content/themes/humanity-theme/includes/theme-setup/analytics/google-tag-manager.php
Ref: No ticket
Internal Slack thread: https://bigbite.slack.com/archives/CBLHK14G7/p1740475955862139
> Fix incorrect GTag call when GTM is not running in consent mode

- private/src/styles/layout/footer/styles/_classic.scss
- private/src/styles/layout/footer/styles/_fse.scss
- private/src/styles/layout/header/shared/_base.scss
- wp-content/themes/humanity-theme/theme.json
Ref: https://github.com/amnestywebsite/humanity-theme/issues/508
1. add a link to some text within a paragraph in the editor
2. the link should be underlined
4. the link should be underlined
> Reenable text decoration for links

- wp-content/themes/humanity-theme/includes/core-blocks/image/filters.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/517
1. testing steps in issue
2. enabling caption visibility for featured image should be resolved by this pr
> Fix output of featured image caption

- private/src/styles/blocks/button/_button.scss
- private/src/styles/blocks/download-block/_editor.scss
- private/src/styles/components/form/_checkbox-group.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/562
1. see issue for repro steps
2. this PR should fix:
- the select element colour in the editor
- the the button element colours on the frontend
- the select element item colour on the frontend
> Fix colours of download block elements within sections

- CHANGELOG.md
- wp-content/themes/humanity-theme/includes/multisite/class-core-site-list.php
- wp-content/themes/humanity-theme/includes/multisite/helpers.php
- wp-content/themes/humanity-theme/style.css
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2994
> Fix site visibility

- private/src/styles/blocks/postlist/_post.scss
- private/src/styles/components/grid/_item.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/593
> Remove text decoration from tag links

- private/src/styles/base/_links.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/600
> Reduce specificity of link decoration selector

- private/src/styles/pages/article/_sidebar.scss
> Constrain iframe widths in sidebars

- wp-content/themes/humanity-theme/includes/helpers/metadata.php
- wp-content/themes/humanity-theme/patterns/attachment-back-link.php
- wp-content/themes/humanity-theme/patterns/attachment-metadata.php
- wp-content/themes/humanity-theme/patterns/attachment-published-date.php
- wp-content/themes/humanity-theme/patterns/attachment-share.php
- wp-content/themes/humanity-theme/patterns/attachment-sidebar.php
- wp-content/themes/humanity-theme/patterns/attachment-term-list.php
- wp-content/themes/humanity-theme/patterns/attachment-updated-date.php
- wp-content/themes/humanity-theme/templates/pdf.html
Ref: N/A
Also https://github.com/amnestywebsite/sharepoint-runner/pull/64
1. view a document on a remote site (e.g. EN on the FR site; AR on the EN site)
2. the document date should be correct
3. the index number should display and be correct
4. the back link should have the correct content type, and should link back correctly to the current site
5. the document terms should be in the current site's language, and link through to terms on the current site
6. the share links should use the correct language document title
7. the sidebar should display correctly
> Fix retrieval of remote attachment data on PDF template parts

- private/src/scripts/modules/overlays.js
- private/src/styles/base/_overlay.scss
- wp-content/themes/humanity-theme/includes/blocks/hero/views/hero.php
- wp-content/themes/humanity-theme/includes/features/search/post-excerpt.php
- wp-content/themes/humanity-theme/includes/full-site-editing/blocks/search-header/views/view.php
- wp-content/themes/humanity-theme/patterns/archive-loop-results.php
- wp-content/themes/humanity-theme/patterns/search-header.php
- wp-content/themes/humanity-theme/patterns/search.php
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2904
> Fix issues relating to new donate workflow

- wp-content/themes/humanity-theme/patterns/attachment-back-link.php
- wp-content/themes/humanity-theme/patterns/attachment-term-list.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/630
1. attempt to load the site editor on a site that is not running MultilingualPress
> Check for MLP function existence before usage in patterns
