amnestywebsite/humanity-theme

- .travis.yml
- private/src/scripts/editor/block-styles/social-links-block.js
- private/src/styles/blocks/core-blocks/_social-links-editor.scss
- private/src/styles/blocks/core-blocks/_social-links.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/36
Removes the social icons brand block styles and moves them to the branding plugin.
Adds margin and removes core transform styles
1. Add social icons block to a page/post
2. Populate with icons
3. In sidebar notice there are no brand related styles
4. Test various styles on the front end
5. Notice margin and hover styles are back to what it should be
Example: http://bigbite.im/v/VQEa96
> Social Icons Block Styles

- private/src/styles/blocks/slider/_main.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/8
Adds a max-width to the slider block to make sure it is contained within the header and footer
1. Add slider block to /latest (Posts Page)
2. Save and view on the front end
3. The slider should NOT extend past the nav bar or footer
Example: http://bigbite.im/i/jgmB3t
> Stop slider extending outside header and footer

- wp-content/themes/humanity-theme/single.php
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2853
If a post has a header block, do not output the featured image
1.  Create a post
2. Add a featured image and a header block
3. Populate the header block with content
4. Save and view the front end
5. Only the header should be displayed
Example: http://bigbite.im/v/wFJAfE
> Conditional Featured Image Output

- private/src/scripts/editor/blocks/post-list/components/DisplayCustom.jsx
- private/src/scripts/editor/blocks/post-list/components/display/LinkList.jsx
- private/src/scripts/editor/blocks/post-list/components/editable/LinkList.jsx
- private/src/styles/blocks/linklist/_editor.scss
- private/src/styles/blocks/linklist/_main.scss
- wp-content/themes/humanity-theme/includes/blocks/post-list/render.php
- wp-content/themes/humanity-theme/includes/blocks/post-list/views/list-item-meta.php
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2780
Recreated from: https://github.com/amnestywebsite/amnesty-wp-theme/pull/2792
Currently, when using the Post List block in `Link List` mode, both the list and grid mode display components are rendered.
Further, the content areas in the list mode component are hard to edit, as they are all collapsed on top of each other.
This PR fixes both issues.
1. First, insert a Post List block into a post, and switch the Type to Custom
2. See that the current issue is as described above
3. Checkout this branch, and rebuild the assets
4. Hard reload the post
5. See that the rendering of the editable components is much improved
6. Switch to grid mode
7. The grid item should render correctly
8. Switch back to list mode …
> Fix render of link list in custom input mode

- private/src/scripts/modules/download-block.js
Props: @gentyspun
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2785
Recreated from: https://github.com/amnestywebsite/amnesty-wp-theme/pull/2849
Adds a conditional to stop the download block breaking the JS bundle
1. Add download block to a post
2. Populate with multiple documents
3. Save and view front end
4. Open dev tools and check no warnings or errors appear relating to the download block
- Testing this requires some specific steps surrounding global media items and media items not included in different language sites.
> Skip download block setup if no elements found

- private/src/styles/blocks/links-with-icons/_group.scss
Props: @gentyspun
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2786
Recreated from: https://github.com/amnestywebsite/amnesty-wp-theme/pull/2841
Removes unnecessary styles that set margin top to zero on 5th and 7th links with icons, causing certain LIW items to sit out of line with the rest
1.  Create a post
2. Add the Links with Icons block
3. Add at least 3 items and populate them with content
4. Save and view the front end
5. All items should sit in line with each other vertically
Example:
http://bigbite.im/i/IqlgiG
> Remove unnecessary margin on LWI items

- private/src/styles/base/_type.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/99
Removes paragraph width limitation.
1. View a country page
2. Paragraphs should extend to the full width of their containers
3. View a News post
4. Paragraphs should extend to the full width of their containers
5. View the homepage
6. Paragraphs should extend to the full width of their containers
> Revert paragraph changes from 48d9bb8

- wp-content/themes/humanity-theme/includes/features/search/permalink.php
Recreated from https://github.com/amnestywebsite/amnesty-wp-theme/pull/2811/
Steps to test:
1. go to `your-domain.tld?s=foo`
2. you should be redirected to `your-domain.tld/search/foo/` without issue
> Add fallback path to search permalink helper

- private/src/scripts/admin.js
- private/src/scripts/admin/options-general.js
- wp-content/themes/humanity-theme/functions.php
- wp-content/themes/humanity-theme/includes/admin/settings-general.php
- wp-content/themes/humanity-theme/includes/helpers/site.php
- wp-content/themes/humanity-theme/includes/mlp/language-selector.php
- wp-content/themes/humanity-theme/includes/multisite/class-core-site-list.php
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2833
Steps to test:
1. go to wp admin -> settings -> general
2. there should be a new field above "site language" labelled "language display name"
3. if it's instead at the bottom of the page, that's a bug
4. put anything in this field and save the settings
5. the field value should populate with the data you entered when you reload the page
6. view the frontend
7. the language selector should show the data you entered instead of the site language name
8. the link should still point to the home page
9. view donate
10. the language selector should show the data you entered instead of the site language name 
11. the link should still point to donate
12. view latest
13. the language selector should show the data you entered …
> Allow language names to be overridden in site options

- private/src/styles/layout/header/shared/_logo.scss
- wp-content/themes/humanity-theme/includes/helpers/media.php
- wp-content/themes/humanity-theme/includes/theme-setup/navigation.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/116
1. before checking out this branch, upload a very wide logo via WP admin -> Theme Options -> Site Logotype (the sample image provided below can be used)
2. view the site frontend
3. you should see that the logo is squashed
4. check out this branch and build assets
5. reload the frontend
6. the logo should have the correct aspect ratio, and not be squished, but it shouldn't fit the available vertical space
7. upload the same image again in WP admin -> Theme Options -> Site Logotype
8. reload the frontend
9. the image should be in the correct aspect ratio, and not be squished. it should also fill the available vertical space, and not overlap any adjacent items
10. remove both the Site Logotype and Site …
> Remove width constraint from, and fix labelling of, site logo

- private/src/styles/blocks/term-list/_main.scss
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2897
1. Navigate to /en/countries/
2. Z should no longer be on a row by itself in the A-Z
Example: http://bigbite.im/i/u9cIew
> A - Z block - make letter boxes larger

- private/src/styles/layout/_page-hero-editor.scss
- private/src/styles/layout/_page-hero.scss
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2884
1. Add a Header block to a post
2. Notice it is smaller than usual, and the "Normal" size option is selected
3. Save and view the front end, it should match the editor
4. Return to the editor and which between Normal and Large to notice the changes in size
5. Then Save for each and check they match on the front end as well
Example: http://bigbite.im/v/aoxZT1
> Header Block - Fix Smaller/Normal size option 

- wp-content/themes/humanity-theme/includes/blocks/term-list/render.php
- wp-content/themes/humanity-theme/includes/helpers/taxonomies.php
- Extract group sorting into helper function
- Sort terms as ASCII
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2893
1. visit countries landing page
2. look at the A-Z list of countries
3. in EN under the `C` group, Côte d'Ivoire should be listed between Congo and Croatia, rather than at the end of the list
4. in ES under the `B` group, Bélgica should appear between Bangladesh and Benín, rather than at the end of the list
5. in FR under the `B` group, Bélarus should appear between Bangladesh and Belgique, rather than at the end of the list
> Adjust sorting of terms in Term List block

- wp-content/themes/humanity-theme/includes/blocks/regions/render.php
- wp-content/themes/humanity-theme/includes/blocks/term-list/render.php
- wp-content/themes/humanity-theme/includes/helpers/taxonomies.php
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2875
In conjunction with: https://github.com/amnestywebsite/wp-plugin-theme-companion/pull/45
1. visit wp admin -> posts -> countries
2. edit a location term
3. the "Hide from blocks" checkbox should no longer be visible
4. edit a post
5. insert a terms list block
6. choose countries as the taxonomy
7. terms that were previously hidden should now be listed*
*To find terms in your db that were previously hidden:
```sql
select t.term_id, t.name from wp_termmeta as m
inner join wp_terms as t on m.term_id = t.term_id
where m.meta_key = 'hidden'
and m.meta_value = 'on'
order by t.name asc
```
> Remove 'hidden' capability from locations

- private/src/styles/pages/article/_base.scss
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2595 Props @Gentyspun
1. View a page or post
2. Check the left and right padding on the article container
3. It should be 40px each side
> Introduce gutters to article containers

- wp-content/themes/humanity-theme/includes/blocks/collapsable/render.php
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2918
1. add a new post
2. insert a collapsable block
3. add some text, make some of it bold/add a link
4. there should be no missing whitespace after the bold/link text
> Replace spaceless with plain output buffering in collapsible block

- wp-content/themes/humanity-theme/includes/theme-setup/text-domain.php
1. checkout branch
2. enable [Humanity Translation Management](https://github.com/amnestywebsite/humanity-translation-management) plugin
3. visit a non-EN site's wp admin
4. go to tools -> translations
5. there should be a tab for the Humanity Theme
6. the tab should list all available translations (see below screenshot)
> Register theme as translatable using Humanity Translation Management

- private/src/scripts/editor/block-styles/group-block.js
- private/src/scripts/editor/block-styles/index.js
- private/src/styles/app.scss
- private/src/styles/blocks/core-blocks/_group.scss
- private/src/styles/gutenberg.scss
- wp-content/themes/humanity-theme/functions.php
- wp-content/themes/humanity-theme/includes/block-patterns/pattern-category.php
- wp-content/themes/humanity-theme/patterns/33-33-33-links-with-icons-square.php
- wp-content/themes/humanity-theme/patterns/33-33-33-links-with-icons.php
- wp-content/themes/humanity-theme/patterns/links-with-icons-single-square.php
- wp-content/themes/humanity-theme/patterns/links-with-icons-single.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/180 https://github.com/amnestywebsite/humanity-theme/issues/181
Adds 2 block patterns, one for a single Links With Icons that can be inserted into columns etc and another that is a pre-built 3 column Links With Icons pattern, also registers a block style for the group block to allow for the old square Links with Icons style
1. Edit a post
2. Open the block inserter and check the new pattern appears under the patterns tab
3. Insert the pattern and check it matches the example in the ticket
4. Also check the new group block styles are present and function as expected (Add a square border around the group in the editor and the front end)
Example: http://bigbite.im/v/RR1cvJ
> Adds links with icons related patterns

- private/src/styles/base/_container.scss
- private/src/styles/pages/_archive.scss
- private/src/styles/pages/article/_base.scss
- wp-content/themes/humanity-theme/archive.php
- wp-content/themes/humanity-theme/includes/helpers/frontend.php
- wp-content/themes/humanity-theme/page-petitions.php
- wp-content/themes/humanity-theme/page.php
- wp-content/themes/humanity-theme/search.php
- wp-content/themes/humanity-theme/searchpage.php
- wp-content/themes/humanity-theme/single.php
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2916
In conjunction with:
- https://github.com/amnestywebsite/wp-plugin-theme-companion/pull/51
- https://github.com/amnestywebsite/sharepoint-runner/pull/33
1. checkout branch and run `yarn build`
2. visit each of the urls listed below
3. for each of the urls:
4. the hero/featured slider (if present) should still be the full width of the container
5. all other content should be indented horizontally by 40px
- /get-involved/
- /get-involved/take-action/
- /who-we-are/
- /latest/
- /latest/news/
- /latest/education/
- /latest/campaigns/
- /latest/impact/
- /latest/research/
- /search/
- /search/[search-term]/
- /countries/
- /location/africa/
- /location/africa/east-africa-the-horn-and-great-lakes/
- …
> Add gutters to most templates

- wp-content/themes/humanity-theme/includes/block-patterns/pattern-category.php
- wp-content/themes/humanity-theme/patterns/25-25-25-25-links-with-icons-square.php
- wp-content/themes/humanity-theme/patterns/25-25-25-25-links-with-icons.php
Creates new four column pattern categories and links with icons patterns containing 4 square border and regular layouts
Ref: https://github.com/amnestywebsite/humanity-theme/issues/181
1. Edit a post
2. Open the block inserter and switch to patterns
3. 2 new categories should appear (Four column & 1/4, 1/4, 1/4, 1/4)
4. Inside those columns will be new 4 column Links with Icons patterns (One with square borders and one without)
5. Insert them both in the post, ensure they both display as expected
Example: http://bigbite.im/i/Mj0Dyq
> 25-25-25-25 Links with Icons patterns

- private/src/scripts/editor/block-filters/hide-unused-blocks.js
- private/src/scripts/editor/blocks/collapsable/index.jsx
Ref: https://github.com/amnestywebsite/humanity-theme/issues/229
Adds a transform.to to the JS block registration of the custom collapsable block to allow it to be changed to a core/details block while retaining the attributes and innerBlocks
1. Edit a post
2. Add a collapsable block (This is now hidden from the block inserter so will need to be added via code editor )
3. Save the post and refresh, now click the block icon in the block toolbar and notice Details appears in the transform options
4. Click Details in the options and the collapsable block should change to a Details block while retaining all the content and attributes
Example: http://bigbite.im/v/vVSMnE
> Add a transforms.to within the custom collapsable block

- private/src/scripts/editor/block-filters/hide-unused-blocks.js
- private/src/styles/app.scss
- private/src/styles/blocks/core-blocks/_details.scss
- private/src/styles/gutenberg.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/231
Style the Core Details block to match the old custom Collapsable block
1. Edit a post
2. Add both a Detail block and Collapsable block (Collapsable has been hidden from the block insterter so use code view to add )
3. Ensure both look the same in terms of styles both in the editor and on the front end
Example: http://bigbite.im/v/DusKN5
> Details Block Humanity Styles

- private/src/scripts/editor/blocks-deprecated/header/DisplayComponent.jsx
- private/src/scripts/editor/blocks/hero/DisplayComponent.jsx
- private/src/styles/blocks/hero/_editor.scss
- private/src/styles/blocks/hero/_main.scss
- private/src/styles/blocks/hero/_styles.scss
- wp-content/themes/humanity-theme/includes/blocks/hero/helpers.php
- wp-content/themes/humanity-theme/includes/blocks/hero/render.php
- wp-content/themes/humanity-theme/includes/blocks/hero/views/hero.php
- wp-content/themes/humanity-theme/page.php
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2950
Note, this PR contains fixes beyond that stated in the referenced ticket. 
Linked: https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/33 & https://github.com/amnestywebsite/humanity-donations/pull/6
1. create a new page
2. insert a hero block
3. add content into each of the fields
4. view the frontend
5. the hero should render correctly in the top area
6. the page title should not be visible
7. edit an existing page that uses an old Header block (e.g. who we are)
8. the block should be converted automatically
9. there should be a notice informing you that the block has been converted
10. save the page
11. view the frontend
12. the page should still render correctly
13. edit the donations …
> Fix Hero rendering issues

- wp-content/themes/humanity-theme/header.php
- wp-content/themes/humanity-theme/page.php
- wp-content/themes/humanity-theme/partials/header.php
- wp-content/themes/humanity-theme/partials/hero.php
- wp-content/themes/humanity-theme/single.php
Experimental fix for Hero / Header output on templates
Steps to test:
1. for each of the following: home page, who we are, what we do, donate, any news post
2. view the item frontend
3. the hero/header should render correctly
4. edit the item and let the block transform occur (if it's still using the old header)
5. save and reload the frontend
6. the hero should render correctly
> Fix output of Hero / Header on posts / pages

- private/src/scripts/editor/blocks/links-with-icons/index.jsx
Ref: https://github.com/amnestywebsite/humanity-theme/issues/120
1. edit a post
2. try to insert a "Links with Icons" block
3. you should be unable to do so
> Hide the LWI block from the inserter

- wp-content/themes/humanity-theme/parts/header.html
Ref: https://github.com/amnestywebsite/humanity-theme/issues/277
Removes pop in and action block from the header template part
1. View the 404 page
2. There should no longer be a pop in or action block within the header
Example: http://bigbite.im/i/wbCwRY
> Removes Pop In from Header Template Part

- wp-content/themes/humanity-theme/includes/blocks/hero/views/hero.php
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2957
1. before checking out this branch
2. add a hero block including a cta with a link
4. try clicking the button
5. it should do nothing
6. switch to this branch
7. reload the frontend
8. click the button
9. it should go to the link defined
> Fix issue with Hero CTA button link

- private/src/styles/components/grid/_editor.scss
- private/src/styles/components/grid/_item.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/279
1. add a post list block in the editor
2. set it to grid mode
3. set it to "custom" content type
4. you should be able to see the tag and title fields
5. add some text into both the tag and title fields, and their respective links
6. once links have been added, you should still be able to see the link icon in the button (previously it appeared to be a blank white box)
7. save the post and view the frontend
8. you should be able to see the post list block
9. you should be able to see both the tag and title content items within the block
10. clicking the tag should take you to the link you set
11. clicking the title should take you to the link you set
> Fix visibility issues with Post List content fields

- private/src/styles/blocks/core-blocks/_blockquote.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/294
Top margins were being overridden on the blockquote, added an important to prevent this happening
1. Edit a post
2. Add paragraphs and a quote block below a paragraph
3. Save and view the front end
4. There should now be margin at the top preventing the quote form touching the paragraph
Example: http://bigbite.im/i/e3SeXT
> Blockquote No Top Margin

- private/src/styles/blocks/core-blocks/_latest-posts.scss
- wp-content/themes/humanity-theme/includes/theme-setup/scripts-and-styles.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/274
Removes a style dependency for the latest posts block and adds an !important to our padding to ensure it is applied to all sides
1. Add the latest posts block to a sidebar
2. Add the sidebar to a post
3. Save and view the front end
4. The latest posts block should have equal and even padding on all sides with no content being cut off
Example: http://bigbite.im/i/ILjhWt
> Latest Posts Sidebar Padding Issue

- wp-content/themes/humanity-theme/patterns/audio-quote.php
- wp-content/themes/humanity-theme/patterns/audio-transcript.php
- wp-content/themes/humanity-theme/patterns/quote-audio.php
Ref: #261 
Creates 3 new patterns for the audio block, 2 with quote blocks (above and below the audio) and one with a details block below to be used for the audio transcript
1. Edit a post
2. Open the block inserter and change the Patterns tab
3. Under the Media category, there should be 3 new patterns related to the Audio block
4. Insert all the patterns, populate with content
5. View them in the editor and the front end to ensure they work correctly and display as expected
Example: http://bigbite.im/v/EZsMev
> Audio/Quote Block Patterns

- CONTRIBUTING.md
- LICENSE.md
Ref: N/A
The `Code of Conduct` link was pointing to the incorrect location, thus making it less accessible from the `CONTRIBUTING.md` file. This PR fixes that by pointing it to the correct file and location on the `main` branch, keeping it inline with other documentation links within the file.
An incorrect file extension in the `LICENSE.md` file has also been corrected to ensure that the url is pointing to the correct full licensing text.
1. N/A
> Correct the Code of Conduct link in the Contributing file.

- wp-content/themes/humanity-theme/header.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/276
1. install browser-sync (`npm i -g browser-sync`)
2. proxy your local environment with browser-sync (`browser-sync start --proxy https://your-domain.tld`)
3. with a phone connected to the same network, visit the access url specified by browser-sync
4. you should see that the site does not respond to your browser width
5. checkout this branch
6. reload the page
7. you should see the small-device layout
> Add missing viewport meta tags

- docs/contributors/code.md
- private/.wp-env.json
- private/package.json
Follow current installation instructions, and then the instructions added [here](https://github.com/amnestywebsite/humanity-theme/pull/342/files#diff-1bc238721e899c47c88c121abe8b2c87a92971b5c0c7929b99f9226d160e0ac3R24).
> Proposal: add option to use wp-env for dev

- private/.wp-env.json
Ref: https://github.com/amnestywebsite/humanity-theme/pull/342#pullrequestreview-2221757571
1. Start the dev environment and deactivate the Humanity Theme if already active (Can be done by running `yarn env run cli wp theme activate twentytwentyfour`).
1. Re-start the dev environment using `yarn env start`
1. Humanity Theme should be active after starting.
- Accessibility
- Regions (semantic HTML tags, e.g. `<section>`; [landmarks](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles#landmark_roles); etc.)
- Screen reader compatibility, labels ([`aria-label`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label), [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attrib …
> wp-env: activate theme after dev env start

- private/.wp-env.json
Follow-up to https://github.com/amnestywebsite/humanity-theme/pull/342 and https://github.com/amnestywebsite/humanity-theme/pull/348
1. Start (or restart) the dev environment using `yarn env start`
1. Visit `/wp-admin/plugins.php` and see that the [required CMB extension plugins](https://github.com/amnestywebsite/humanity-theme?tab=readme-ov-file#required-plugins) are present and activated
n/a
> Adds CMB extensions to wp-env configuration

- LICENSE.md
- OFL.txt
Ref: N/A
The theme bundles the Lato and Playfair Display fonts, for which we are currently missing the licence text. This PR adds the OFL text.
> Add the Open Font Licence text

- private/src/scripts/editor/block-styles/group-block.js
- private/src/styles/app.scss
- private/src/styles/block-patterns/_group.scss
- private/src/styles/gutenberg.scss
- wp-content/themes/humanity-theme/patterns/custom-card-dark.php
- wp-content/themes/humanity-theme/patterns/custom-card-light.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/287
Creates two new block patterns to replace the custom card block on the theme
1. Edit a post
2. Open the block inserter
3. There should now be 2 patterns for a "Light" and "Dark" custom cards
4. Insert both and check they display correctly in the editor and on the front end
5. Return to the editor and highlight the group block, notice 2 new blocks styles for light and dark
6. Use the alignment dropdown in the block toolbar to change between regular and wide block pattern variations
Branding patterns and block styles can be found in branding plugin PR [here](https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/41).
Example: http://bigbite.im/v/WnXOBg
> Custom Card Block Pattern

- private/src/styles/base/_base.scss
- private/src/styles/base/_links.scss
- wp-content/themes/humanity-theme/theme.json
Ref: https://github.com/amnestywebsite/humanity-theme/issues/337
Small PR to move some more typography settings to theme.json.
1. Ensure the primary font family is correctly used on the front-end and the Editor.
2. Ensure the main font colour is still the same.
3. Ensure all links outside of articles look the same (colour and text-decoration).
- Accessibility
- Regions (semantic HTML tags, e.g. `<section>`; [landmarks](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles#landmark_roles); etc.)
- Screen reader compatibility, labels ([`aria-label`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label), [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-lab …
> Move more font CSS to theme.json

- wp-content/themes/humanity-theme/includes/blocks/_deprecated/header/class-header-block-renderer.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/272
Adds a conditional check to make sure the header/hero has an image ID before outputting, preventing an empty block being output which was causing a large amount of white space
1. Edit the latest page
2. Insert a header block using the code editor (or by checking out a branch without the new hero block first)
3. Save and switch to this branch
4. Open Latest on the front end
5. The hero/header should display correctly with no white space/empty block
Example: http://bigbite.im/i/5Es2hI
> Fix white space below Header/Hero block

- wp-content/themes/humanity-theme/includes/helpers/taxonomies.php
This does nothing by itself in the theme.
However, in conjunction with a filter in
the Theme Companion, it allows for report
terms to be filtered out from term lists.
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2967
1. test in conjunction with https://github.com/amnestywebsite/wp-plugin-theme-companion/pull/59
2. visit the /countries/ page
3. the a-z should not include apparently-duplicate country names
4. the explore by region section should only list regions and subregions
5. country pages should include links to their annual report
6. clicking the link to the annual report should render the report page correctly
7. visit /latest/
8. click the countries dropdown
9. it should not list duplicate country names
10. edit a country term
11. the checkbox …
> Add flag to filter report terms

- private/src/scripts/editor/blocks/blockquote/index.jsx
- private/src/styles/app.scss
- private/src/styles/blocks/core-blocks/_quote.scss
- private/src/styles/editor.scss
- wp-content/themes/humanity-theme/theme.json
Ref: #314 
Adds the core/quote block back, adds typography style options (like color palette and font size) into the block via theme.json and adds custom styles
1. Edit a post
2. Open the block inserter and search for quote
3. The core block should now be available
4. Insert it and populate with content
5. Play around with customise options to ensure all functionality from original custom block is available
6. Save and view the front end
7. Now test the transform by checking out the Branding Plugin Branch
Example: http://bigbite.im/v/H9bBd9
> Adds Core Quote Block and Styles

- private/src/styles/blocks/section/_editor.scss
- private/src/styles/blocks/section/_main.scss
- private/src/styles/pages/_single.scss
- private/src/styles/pages/article/_base.scss
Fixes issue with broken padding on sections with FSE changes by removing a now unnecessary css rule.
Also fixes the text colour not changing in the Editor for Full Image with Buttons pattern
1. For section padding, navigate the front end of the site and check the padding is correct on pages and posts
2. For text colour change, edit a post and insert the Full Image with Buttons pattern
3. Highlight the section and change the text colour
4. The heading should now change accordingly
Example: 
Padding: http://bigbite.im/i/gAfRu2
Text Colour: http://bigbite.im/v/sTqUtn
> Section Padding and Full Image with Buttons Pattern text colour

- wp-content/themes/humanity-theme/patterns/66-33-text-with-image.php
- wp-content/themes/humanity-theme/patterns/audio-quote.php
- wp-content/themes/humanity-theme/patterns/quote-audio.php
Replaces all instances of the custom quote block with the core quote block in patterns
1. Edit a post
2. Open the block/pattern inserter
3. Search Quote
4. Insert all the patterns containing quote blocks
5. Notice they now use the core quote block instead of the custom quote block
Example: http://bigbite.im/i/lDVRtN
> Replaces custom quote with core quote in patterns

- private/src/styles/blocks/postlist/_main.scss
- private/src/styles/blocks/postlist/_post.scss
Fixes post list styling for country pages
1. Navigate to a country page/region or sub-region
2. Scroll to the News, Urgent Actions or Research sections
3. They should now appear as expected
4. Reduce the window size and they should respond as expected also
Example: http://bigbite.im/v/oXji2R
> Fixes post list styling for country pages

- private/src/styles/blocks/stat-counter/_main.scss
Fixes the line height issue with the counter block, by overriding theme.json default line height value
1. Edit a post and insert a counter block
2. Populate with content
3. Save and view the front end
4. No elements should now overlap and should be spaced correctly
Example: http://bigbite.im/i/V7EtOX
> Counter Block Line Height

- private/src/styles/pages/_single.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/327
Fixes the spacing issue on Article Meta Actions for RTL users
1. Navigate to a post (either on /ar or you can change the ltr body class in dev tools)
2. Scroll down to just before Related Content
3. Notice the spacing between the social share and terms buttons
Example: http://bigbite.im/i/O8dm3g
> Fix Article Meta Action Spacing for RTL

- private/src/styles/layout/_page-hero.scss
- wp-content/themes/humanity-theme/includes/kses/wp-kses-post.php
- wp-content/themes/humanity-theme/patterns/featured-image.php
- wp-content/themes/humanity-theme/patterns/post-header.php
- wp-content/themes/humanity-theme/templates/single.html
Style tag was being escaped, leaving the CSS
to be output as a string.
This fix allows the style tag to be output
without being stripped by KSES only whilst
the header block is being rendered.
Since the CSS being rendered is properly
escaped in the renderer, this should be
acceptable.
1. Visit a page that's using the old header block, or add it via code view
2. View the frontend
3. the styles should be output correctly - the background image on the block should render
> Fix old header rendering

- wp-content/themes/humanity-theme/includes/core-blocks/query/pagination/numbers.php
1. visit the search page (no search term)
2. click on a page number
3. you should remain on the search page 
4. the uri suffix should be `/page/n/`, where `n` is the number you clicked
> Fix page number URIs on searchpage

- private/src/styles/blocks/core-blocks/_image.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/323
Fixes an issue with image meta data extending outside the limits of the image if image size is small
1. Edit a post
2. Insert an image block and pick an image
3. Change the image size to something small (hero small or image block for example)
4. Save and view the frontend
5. Image meta (Caption and Credit) should be contained within image size and not extend outside of it
Example: http://bigbite.im/i/Jo4bDS
> Bug - Image - Copyright field overhangs the picture

- wp-content/themes/humanity-theme/functions.php
- wp-content/themes/humanity-theme/includes/features/search/class-search-results.php
Ref: N/A
1. before checking out this pr
2. disable the sharepoint plugin
3. perform a search
4. filter the results by year/month/taxonomy
5. the filters should not be applied
6. checkout this pr
7. reload your search
8. the filters should be correctly applied
> Fix missing application of search filters

- wp-content/themes/humanity-theme/includes/helpers/post-single.php
- wp-content/themes/humanity-theme/patterns/featured-image.php
If Multisite Global Media is enabled and
used for the featured image, it will fail
to render.
Ref: https://github.com/amnestywebsite/humanity-theme/issues/384
1. assuming multisite global media plugin is enabled
2. before checking out, insert an image from the global media library to a post featured image
4. the image won't render
5. checkout this PR
6. reload the frontend
7. the image should load
> Retrieve featured image correctly

- CHANGELOG.md
- wp-content/themes/humanity-theme/includes/features/search/class-search-page.php
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2987
1. visit the search page
2. filter by "urgent action" resource type
3. sharepoint docs should show in the results
> Add documents into search page query

- private/src/styles/blocks/postlist/_post-editor.scss
- private/src/styles/gutenberg.scss
Ref: https://github.com/amnestywebsite/humanity-petitions/issues/13
1. edit a post
2. insert a post list block / petition list block
3. switch to object selection mode
4. each item in the list of objects to choose from should not be inordinately large
5. the content within each item (image, title, plus button) should be aligned nicely
6. hovering over an item should now indicate the current item with a subtle background colour, in addition to the plus button
> Fix appearance of post list in block editor

- private/src/styles/blocks/postlist/_categories-editor.scss
- private/src/styles/blocks/postlist/_categories.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/457
Ensures the padding is added to the menu block in both the editor and on the front end
1. Edit a post
2. Add the menu block and pick a menu
3. Change background to grey for more visibility
4. Notice the padding in the editor
5. Save or preview on the front end
6. Notice the padding on the front end
Example:
Frontend: http://bigbite.im/i/8hnwRN
Editor: http://bigbite.im/i/ZUN7m0
> Menu block padding fix

- private/src/styles/block-patterns/_group.scss
- wp-content/themes/humanity-theme/patterns/custom-card-dark.php
- wp-content/themes/humanity-theme/patterns/custom-card-light.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/287
Changes custom card pattern to fill any container, and removes constraints from pattern
1. Edit a post
2. Add a custom card pattern (Dark or Light, Brand has separate PR on the plugin)
3. Notice it fills the whole content area width
4. Add a column block and insert a custom card
5. Notice it fills the column
6. Save and check the same applies for the front end
Example: http://bigbite.im/v/HNQD6h
> Custom Card Pattern Fill Container

- wp-content/themes/humanity-theme/includes/theme-setup/navigation.php
props: @valentin-dassonville
Ref: https://github.com/amnestywebsite/humanity-theme/issues/477
1. prior to checkout, enable `WP_DEBUG` and
2. go to wp-admin -> appearance -> menus
3. unassign any menu set to the `footer-navigation` menu location, if any
4. unassign any menu set to the `footer-legal` menu location, if any
5. view the frontend
6. you should see warnings similar to those shown in the screenshot in the linked ticket
7. checkout this PR
8. the warnings should no longer appear
> Add extra check into menu items' retrieval helper

- private/src/scripts/editor/blocks/stat-counter/DisplayComponent.jsx
- private/src/scripts/modules/counter.js
- private/src/styles/admin/_localisation-options.scss
- wp-content/themes/humanity-theme/includes/admin/theme-options/localisation.php
- wp-content/themes/humanity-theme/includes/blocks/stat-counter/render.php
- wp-content/themes/humanity-theme/includes/theme-setup/scripts-and-styles.php
Epic: https://github.com/amnestywebsite/humanity-theme/issues/417
Issue: https://github.com/amnestywebsite/humanity-theme/issues/5
Adds a checkbox to the localisation tab inside Theme Options that forces the use of thousand separators on the stats counter block.
1. Before checking out this branch, edit a post on /es/
2. Insert a counter block and populate with a number > 999 but < 10,000
3. Save and view the front end.
4. Notice the number will have no thousand separator.
5. Checkout this branch and run a build
6. Go to es/wp-admin/admin.php?page=amnesty_localisation_options_page
7. There should now be a checkbox for "Force Thousands Separator"
8. Check this, and save.
9. Now return to your counter block front end and refresh
10. The number should now display with a …
> Add Option for forcing thousand separator for stats counter block

- wp-content/themes/humanity-theme/includes/theme-setup/wp-head.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/523
1. Set the site home page to a static page
2. Visit the home page
3. Check that the output in the `<title>` tag is the site name
> Set title fallback to blog name

- private/src/styles/blocks/petition-list/_main.scss
- wp-content/themes/humanity-theme/includes/blocks/petition-list/render.php
WP's word-count truncation truncates characters in Thai, rather than words. Other truncation methods using PHP string manipulation may work, but it is unnecessary computation if we can do the same in CSS.
Although the CSS method does use '-webkit-' browser vendor prefixes, they are supported in all major
browsers (as the spec is still in draft). so this
should allow for a similar experience in modern
browsers, without causing too much layout shift in browsers that don't support it. So it's a reasonable compromise in this specific scenario.
Ref: https://github.com/amnestywebsite/humanity-theme/issues/525
1. add a petition with a very long title
2. if testing on the "main" site, view the petitions index, and skip to step 5, else skip this step
3. insert a petitions list …
> Move petition title truncation to CSS

- wp-content/themes/humanity-theme/includes/blocks/petition-list/register.php
Ref: N/A
1. before checking out this PR
2. create a petition
3. add a new post
4. insert a petitions list block and save
5. go to settings -> permalinks
6. change the petition url slug to something other than the default of `petition`
7. go to the petitions list view 
8. if the list is empty, the slug didn't update correctly (separate bug), so run `update wp_posts set post_type = 'your-new-slug' where post_type = 'petition';
9. reload the list
10. your petition(s) should be visible again
11. edit the post you created in step 3
12. the petitions list block should still load items
13. preview the post
14. the petitions list block should not render any items
15. checkout this PR
16. reload the post preview
17. the petitions should load
> Fix incorrect slug reference in Petitions List block

- private/src/styles/layout/navigation/shared/_desktop.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/480
1. visit an RTL site
2. hover over a main menu item that has sub-items
3. the sub-item list should become visible
4. the sub-menu list should be anchored to the left of the parent item's box
> Adjust anchor point for submenus in RTL

- private/src/styles/components/grid/_item.scss
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/3025
This PR increases the breakpoint at which the grid moves from a single column to multiple columns
1. prior to checking out this pr
2. insert some post list blocks, in grid mode, containing varying numbers of items
4. as you reduce the viewport width, you should see a point at which the post list pushes past the edge of the container, before eventually collapsing into one item per row at very small sizes
5. checkout this pr and run a build
6. perform step 4 again; this time, the grid should collapse down before it reaches the point at which it overflows the container
> Adjust grid breakpoints

- wp-content/themes/humanity-theme/includes/blocks/iframe/views/responsive-iframe.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/563
1. insert a responsive iframe block
2. add any iframe url
3. add a caption that has some text formatting (bold, italic, href, etc)
4. view the frontend
5. the caption should render correctly
> Change escaping method for Responsive Iframe caption

- private/src/styles/components/grid/_editor.scss
- private/src/styles/components/grid/_item.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/513
Ensures post list grid label text is always white
1. Insert a post list and change the style to GRID
2. Change the type to CUSTOM
3. Enter label text and it should be white, BUT do not link the text
4. Save the post and view the front end
5. The label text should now be white and visible against the background
6. Change the type to CATEGORY and choose a category
7. Labels should now be white in the editor here as well
Example: http://bigbite.im/v/we3uUF
> Bug - Post list grid, custom, label only works if a hyperlink is present

- private/src/styles/layout/footer/styles/_fse.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/576
Removes unnecessary color css from footer social icons
1.  Edit the footer template part
2. Select the social icons and insert a Threads block
3. Add a profile link or #
4. Save and view the front end
5. The threads logo should now be white and visible
Example: http://bigbite.im/i/A30yDB
> Bug - Social Icons - Threads icon does not appear on the front end

- composer.json
Ref: N/A
1. run `composer updatePoMo`
2. see that `*.l10n.php` files are created
3. disable the translation management plugin, if enabled
4. install and activate query monitor
5. load the frontend
6. open query monitor's languages tab
7. look for the inclusion of the `*.l10n.php` file (see below screenshot)
> Add command to compile l10n PHP files

- private/src/styles/blocks/button/styles/_default.scss
- private/src/styles/components/_icon.scss
- private/src/styles/pages/article/_share.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/491
Ensures the left arrow on the meta block on posts has the correct hover styles
1. Navigate to a single post on the front end
2. Look for the meta block back button (e.g. < Campaigns)
3. Hover and notice that the arrow is still visible
Example: http://bigbite.im/v/6UZ3Rn
> Bug - meta block - back button arrow not showing on hover

- private/src/styles/base/_images.scss
- wp-content/themes/humanity-theme/includes/theme-setup/scripts-and-styles.php
Ref: Supports https://github.com/amnestywebsite/humanity-theme/issues/575
The current URI is relative to the stylesheet; so, if a plugin (for example) were to reference it, the URI would be incorrect.
1. before checking out this PR
2. reference `--amnesty-icon-path` in a plugin (example CSS below)
4. see a 404 in console/network in dev tools
5. checkout this PR
6. reload the frontend
7. the 404 should disappear
> Set icon path to fully-qualified URI

- private/src/styles/blocks/slider/_main.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/15
1. insert a slider with several slides
2. view the frontend
3. the "next slide" indicator arrow should be visible
4. the "previous slide" indicator arrow should not be visible
5. clicking the "next slide" arrow should navigate you to the next slide
6. the "previous slide" arrow should become visible
7. clicking the "previous slide" arrow should navigate you to the previous slide
8. the "previous slide" arrow should then hide again
9. the "next slide" arrow should remain visible
10. navigate to the last slide
11. the "next slide" arrow should hide
12. the "previous slide" arrow should remain visible
13. edit the post
14. in the sidebar options for the slider block
15. toggle the "show tabs" option off
16. …
> Fix initial display of slider navigation arrows

- wp-content/themes/humanity-theme/includes/mlp/helpers.php
- wp-content/themes/humanity-theme/includes/multisite/class-core-site-list.php
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/2994
1. in network admin, edit a site
2. under the "attributes" section of the "info" tab, untick the `public` checkbox & save
3. view the home page
4. hover over the language selector dropdown
5. the site should not be in the list of available translations
6. open an incognito window
7. visit the site
8. the site you've marked as not public should no longer be visible in the language selection banner
> Ensure content is from sites marked as public

- wp-content/themes/humanity-theme/includes/helpers/site.php
- wp-content/themes/humanity-theme/includes/taxonomies/class-taxonomy-resource-types.php
- wp-content/themes/humanity-theme/includes/taxonomies/class-taxonomy-topics.php
Ref: https://github.com/amnestywebsite/amnesty-wp-theme/issues/3029
we have previously assumed language codes to be two letters, e.g. `es`, `ar`; however, with the introduction of support for Chinese, we can't make that assumption any more. this PR implements changes that allow for language codes such as `zh-Hant`.
1. before checking out this pr
2. create a site in `zh` with the language code `zh-hant` (via MLP), and the url path of `/zh-hant/`; copy across content, but skip attachments
3. attempt to visit a topic uri, e.g. `/zh-hant/topic/armed-conflict/`
4. it should 404
5. attempt to visit a resource type uri, e.g. `/zh-hant/resource-type/action/`
6. it should 404
7. checkout this pr
8. reload the 404 page in step 3
9. it should redirect to search with the topic id …
> Fix support for language codes

- wp-content/themes/humanity-theme/includes/blocks/download/views/multiple.php
When manually adding multiple files with the same Index Number, the files array is associative, rather than a list, so array access throws warnings.
This PR changes the behaviour, so that the type of array isn't assumed.
> Prevent array access errors in download block

- wp-content/themes/humanity-theme/includes/blocks/post-list/views/grid-item-meta.php
Ref: https://github.com/amnestywebsite/humanity-theme/issues/597
1. add a post
2. insert a post list block
3. set the style to **grid**
4. set the type to **custom**
5. add a few items
6. input nothing in the tag field for one item
7. input only text in the tag field for one item
8. input only a link in the tag field for one item
9. input both text and a link in the tag field for one item
10. save the post
11. preview the frontend
12. only on items where there is text in the tag field should the tag area be output
> Prevent output of Post List tag if it has no text

- private/src/styles/base/_links.scss
Ref: https://github.com/amnestywebsite/humanity-theme/issues/611
1. view a post single
2. check that links within the post content are underlined
3. check that tags, back buttons, sidebar items, etc. are not underlined
- Accessibility
- Regions (semantic HTML tags, e.g. `<section>`; [landmarks](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles#landmark_roles); etc.)
- Screen reader compatibility, labels ([`aria-label`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label), [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby), etc.)
- Keyboard navigability
- Localisation
- RTL
> Only allow text decoration on text anchors
